FROM postgres:15.1-alpine

LABEL version="1.0.0"
LABEL maintainer="Team_P"

WORKDIR /.

ADD database/postgres.d/init.sql /docker-entrypoint-initdb.d/

RUN chmod 755 /docker-entrypoint-initdb.d/init.sql